### ISSUE TITLE
The token generate command error

### ISSUE THREAD

**Issue by aaronchn** [kumekay/inlets-compose#1]
OS：Debian Buster/10

In Shell:
```
$ pwd
/home/userx
$ head -c 16 /dev/urandom | shasum | cut -d\" \" -f1
cut: '"': No such file or directory
```
Try:
```
$ head -c 16 /dev/urandom | shasum | cut -d"=" -f2
c8aa0836f7a4030ee4b493a56854fd02792f9d51
```

**Comment by kumekay** [comment]
@aaronchn Aaron, thank you for the issue, I've updated to `head -c 16 /dev/urandom | shasum | cut -d' ' -f1` that should work fine on different linuxes and macos. Not sure why I escaped quotes initally...
